"""addres table latitude and longtitude

Revision ID: 02db9c1fa6a0
Revises: 09beea094456
Create Date: 2022-05-01 14:52:10.977219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db9c1fa6a0'
down_revision = '09beea094456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
