"""addres table latitude and longtitude

Revision ID: 09beea094456
Revises: 8e0ded9a41b1
Create Date: 2022-05-01 14:25:01.772241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09beea094456'
down_revision = '8e0ded9a41b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
