"""addres table updated

Revision ID: 8e0ded9a41b1
Revises: 19330d5a83e4
Create Date: 2022-05-01 01:00:04.413869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0ded9a41b1'
down_revision = '19330d5a83e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address_label', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone_no', sa.String(length=25), nullable=True),
    sa.Column('pincode', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'probile_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('probile_url', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_table('Address')
    # ### end Alembic commands ###
